
project_id = "nsxxzhhbcwzatvlulfyp"

[functions.discover-artists]
verify_jwt = false

[functions.process-album-page]
verify_jwt = false

[functions.process-track-page]
verify_jwt = false

[functions.identify-producers]
verify_jwt = false

[functions.maintenance]
verify_jwt = false
